/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.controle.view;

import com.controle.dao.CondominioDAO;
import com.controle.dao.DAOFactory;
import com.controle.modelo.Condominio;
import com.utilitarios.Formatados;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Daniel
 */
public class FrmCadCondominio extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCadCondominio
     *
     * @throws java.text.ParseException
     */
    public FrmCadCondominio() throws ParseException {
        initComponents();
        Formatados.mascara(jFormattedTextFieldCep, "#####-###");
        Formatados.mascara(jFormattedTextFieldFone, "(##)####-####");
        Formatados.mascara(jFormattedTextFieldCnpj, "##.###.###/####-##");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jFormattedTextFieldCep = new javax.swing.JFormattedTextField();
        jFormattedTextFieldFone = new javax.swing.JFormattedTextField();
        jTextFieldUf = new javax.swing.JTextField();
        jTextFieldInstrucao1 = new javax.swing.JTextField();
        jTextFieldInstrucao2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldInstrucao3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldInstrucao4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jFormattedTextFieldMora = new javax.swing.JFormattedTextField();
        jFormattedTextFieldMulta = new javax.swing.JFormattedTextField();
        jFormattedTextFieldRateio = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldSindico = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jFormattedTextFieldCnpj = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldDiaVencto = new javax.swing.JTextField();

        setClosable(true);

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Endereço:");

        jLabel4.setText("Bairro:");

        jLabel5.setText("Cidade:");

        jLabel6.setText("Cep:");

        jLabel7.setText("Telefone:");

        jLabel8.setText("Estado:");

        jLabel9.setText("Instrução 1:");

        jLabel10.setText("Instrução 2:");

        jTextFieldCodigo.setEnabled(false);

        jTextFieldNome.setEnabled(false);

        jTextFieldEndereco.setEnabled(false);

        jTextFieldBairro.setEnabled(false);

        jTextFieldCidade.setEnabled(false);

        jFormattedTextFieldCep.setEnabled(false);

        jFormattedTextFieldFone.setEnabled(false);

        jTextFieldUf.setEnabled(false);

        jTextFieldInstrucao1.setEnabled(false);

        jTextFieldInstrucao2.setEnabled(false);

        jLabel11.setText("Instrução 3:");

        jTextFieldInstrucao3.setEnabled(false);

        jLabel12.setText("Instrução 4:");

        jTextFieldInstrucao4.setEnabled(false);

        jLabel13.setText("Juros Mora:");

        jLabel14.setText("Multa:");

        jLabel15.setText("Rateio:");

        jFormattedTextFieldMora.setEnabled(false);

        jFormattedTextFieldMulta.setEnabled(false);

        jFormattedTextFieldRateio.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel16.setText("Cadastro Condomínios");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controle/imagens/add.png"))); // NOI18N
        jButtonNovo.setToolTipText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controle/imagens/accept.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controle/imagens/application_remove.png"))); // NOI18N
        jButtonExcluir.setToolTipText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controle/imagens/home_next.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controle/imagens/search.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controle/imagens/application_edit.png"))); // NOI18N
        jButtonEditar.setToolTipText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jTextFieldPesquisa.setToolTipText("Pesquisar Código");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSair, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonNovo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jButtonEditar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonExcluir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldPesquisa))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSair)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controle/imagens/skip_backward.png"))); // NOI18N
        jButtonPrimeiro.setToolTipText("Primeiro");
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controle/imagens/rewind.png"))); // NOI18N
        jButtonAnterior.setToolTipText("Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controle/imagens/fast_forward.png"))); // NOI18N
        jButtonProximo.setToolTipText("Próximo");
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controle/imagens/skip_forward.png"))); // NOI18N
        jButtonUltimo.setToolTipText("Último");
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPrimeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUltimo)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrimeiro)
                    .addComponent(jButtonAnterior)
                    .addComponent(jButtonProximo)
                    .addComponent(jButtonUltimo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setText("Síndico:");

        jTextFieldSindico.setEnabled(false);

        jLabel18.setText("Cnpj:");

        jFormattedTextFieldCnpj.setEnabled(false);

        jLabel19.setText("Email:");

        jTextFieldEmail.setEnabled(false);

        jLabel20.setText("Dia Vencimento:");

        jTextFieldDiaVencto.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel5))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextFieldSindico, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(7, 7, 7)
                                            .addComponent(jLabel18)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldCidade))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(7, 7, 7)
                                    .addComponent(jLabel20)
                                    .addGap(3, 3, 3)
                                    .addComponent(jTextFieldDiaVencto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jFormattedTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jFormattedTextFieldMora)
                                        .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldUf)
                                        .addComponent(jFormattedTextFieldMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel15))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jFormattedTextFieldFone)
                                        .addComponent(jFormattedTextFieldRateio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldInstrucao4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldInstrucao3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldInstrucao2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldInstrucao1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(99, 99, 99)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jFormattedTextFieldFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jFormattedTextFieldMora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldRateio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextFieldSindico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jFormattedTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jTextFieldDiaVencto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldInstrucao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldInstrucao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldInstrucao3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldInstrucao4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void desbloquearCampos() {
        jTextFieldNome.setEnabled(true);
        jTextFieldEndereco.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jFormattedTextFieldCep.setEnabled(true);
        jTextFieldUf.setEnabled(true);
        jFormattedTextFieldFone.setEnabled(true);
        jFormattedTextFieldMora.setEnabled(true);
        jFormattedTextFieldMulta.setEnabled(true);
        jFormattedTextFieldRateio.setEnabled(true);
        jTextFieldSindico.setEnabled(true);
        jFormattedTextFieldCnpj.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jTextFieldDiaVencto.setEnabled(true);
        jTextFieldInstrucao1.setEnabled(true);
        jTextFieldInstrucao2.setEnabled(true);
        jTextFieldInstrucao3.setEnabled(true);
        jTextFieldInstrucao4.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }

    private void bloquearCampos() {
        jTextFieldNome.setEnabled(false);
        jTextFieldEndereco.setEnabled(false);
        jTextFieldBairro.setEnabled(false);
        jTextFieldCidade.setEnabled(false);
        jFormattedTextFieldCep.setEnabled(false);
        jTextFieldUf.setEnabled(false);
        jFormattedTextFieldFone.setEnabled(false);
        jFormattedTextFieldMora.setEnabled(false);
        jFormattedTextFieldMulta.setEnabled(false);
        jFormattedTextFieldRateio.setEnabled(false);
        jTextFieldSindico.setEnabled(false);
        jFormattedTextFieldCnpj.setEnabled(false);
        jTextFieldEmail.setEnabled(false);
        jTextFieldDiaVencto.setEnabled(false);
        jTextFieldInstrucao1.setEnabled(false);
        jTextFieldInstrucao2.setEnabled(false);
        jTextFieldInstrucao3.setEnabled(false);
        jTextFieldInstrucao4.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        desbloquearCampos();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        String v = "0,00";
        Condominio c = new Condominio();
        c.setNomeCondominio(jTextFieldNome.getText());
        c.setEnderecoCondominio(jTextFieldEndereco.getText());
        c.setBairroCondominio(jTextFieldBairro.getText());
        c.setCidadeCondominio(jTextFieldCidade.getText());
        c.setCepCondominio(jFormattedTextFieldCep.getText());
        c.setUfCondominio(jTextFieldUf.getText());
        c.setFoneCondominio(jFormattedTextFieldFone.getText());
        String valor1 = validarDoubleValor(jFormattedTextFieldMora);
        if (valor1 != null) {
            c.setMoraCondominio(Double.parseDouble(valor1));
        } else {
            c.setMoraCondominio(Double.parseDouble(v));
        }
        String valor2 = validarDoubleValor(jFormattedTextFieldMulta);
        if (valor2 != null) {
            c.setMultaCondominio(Double.parseDouble(valor2));
        } else {
            c.setMultaCondominio(Double.parseDouble(v));
        }
        String valor3 = validarDoubleValor(jFormattedTextFieldRateio);
        if (valor3 != null) {
            c.setRateioCondominio(Double.parseDouble(valor3));
        } else {
            c.setRateioCondominio(Double.parseDouble(v));
        }
        c.setSindicoCondominio(jTextFieldSindico.getText());
        c.setCnpjCondominio(jFormattedTextFieldCnpj.getText());
        c.setEmailCondominio(jTextFieldEmail.getText());
        c.setDiaVencimento(jTextFieldDiaVencto.getText());
        c.setInstrucao1(jTextFieldInstrucao1.getText());
        c.setInstrucao2(jTextFieldInstrucao2.getText());
        c.setInstrucao3(jTextFieldInstrucao3.getText());
        c.setInstrucao4(jTextFieldInstrucao4.getText());

        if (jTextFieldNome.getText().isEmpty() || jTextFieldSindico.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Nome ou Síndico estão vazios, favor preencher!");
        } else {
            CondominioDAO j = DAOFactory.getDAOFactory().getCondominioDAO();
            j.salvar(c);
            JOptionPane.showMessageDialog(null, "Condomínio Salvo com Sucesso!");
            limparCampos();
            bloquearCampos();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed


    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        String vazio = "";
        if (jTextFieldPesquisa.getText().equals(vazio)) {
            JOptionPane.showMessageDialog(null, "É necessário informar um código para ser pesquisado!");
        } else {
            CondominioDAO j = DAOFactory.getDAOFactory().getCondominioDAO();
            int a = Integer.parseInt(jTextFieldPesquisa.getText());

            try {
                Condominio condominio = j.buscarPeloCodigo(a);
                jTextFieldCodigo.setText(condominio.getCodCondominio().toString());
                jTextFieldNome.setText(condominio.getNomeCondominio());
                jTextFieldEndereco.setText(condominio.getEnderecoCondominio());
                jTextFieldBairro.setText(condominio.getBairroCondominio());
                jTextFieldCidade.setText(condominio.getCidadeCondominio());
                jTextFieldUf.setText(condominio.getUfCondominio());
                jFormattedTextFieldCep.setText(condominio.getCepCondominio());
                jFormattedTextFieldFone.setText(condominio.getFoneCondominio());
                jFormattedTextFieldCnpj.setText(condominio.getCnpjCondominio());
                jTextFieldEmail.setText(condominio.getEmailCondominio());
                jTextFieldSindico.setText(condominio.getSindicoCondominio());
                jTextFieldInstrucao1.setText(condominio.getInstrucao1());
                jTextFieldInstrucao2.setText(condominio.getInstrucao2());
                jTextFieldInstrucao3.setText(condominio.getInstrucao3());
                jTextFieldInstrucao4.setText(condominio.getInstrucao4());
                jFormattedTextFieldMora.setText(condominio.getMoraCondominio().toString());
                jFormattedTextFieldMulta.setText(condominio.getMultaCondominio().toString());
                jFormattedTextFieldRateio.setText(condominio.getRateioCondominio().toString());
                jTextFieldDiaVencto.setText(condominio.getDiaVencimento());
                jButtonNovo.setEnabled(false);
                desbloquearCampos();
                jButtonSalvar.setEnabled(false);
                //System.out.println("Registro Encontrado!");
            } catch (Exception e) {
                limparCampos();
                JOptionPane.showMessageDialog(null, "Registro não existe!");
                //System.out.println("Erro: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        String v = "0,00";
        Condominio c = new Condominio();

        c.setNomeCondominio(jTextFieldNome.getText());
        c.setEnderecoCondominio(jTextFieldEndereco.getText());
        c.setBairroCondominio(jTextFieldBairro.getText());
        c.setCidadeCondominio(jTextFieldCidade.getText());
        c.setCepCondominio(jFormattedTextFieldCep.getText());
        c.setUfCondominio(jTextFieldUf.getText());
        c.setFoneCondominio(jFormattedTextFieldFone.getText());
        String valor1 = validarDoubleValor(jFormattedTextFieldMora);
        if (valor1 != null) {
            c.setMoraCondominio(Double.parseDouble(valor1));
        } else {
            c.setMoraCondominio(Double.parseDouble(v));
        }
        String valor2 = validarDoubleValor(jFormattedTextFieldMulta);
        if (valor2 != null) {
            c.setMultaCondominio(Double.parseDouble(valor2));
        } else {
            c.setMultaCondominio(Double.parseDouble(v));
        }
        String valor3 = validarDoubleValor(jFormattedTextFieldRateio);
        if (valor3 != null) {
            c.setRateioCondominio(Double.parseDouble(valor3));
        } else {
            c.setRateioCondominio(Double.parseDouble(v));
        }
        c.setSindicoCondominio(jTextFieldSindico.getText());
        c.setCnpjCondominio(jFormattedTextFieldCnpj.getText());
        c.setEmailCondominio(jTextFieldEmail.getText());
        c.setDiaVencimento(jTextFieldDiaVencto.getText());
        c.setInstrucao1(jTextFieldInstrucao1.getText());
        c.setInstrucao2(jTextFieldInstrucao2.getText());
        c.setInstrucao3(jTextFieldInstrucao3.getText());
        c.setInstrucao4(jTextFieldInstrucao4.getText());
        c.setCodCondominio(Integer.parseInt(jTextFieldCodigo.getText()));

        if (jTextFieldNome.getText().isEmpty() || jTextFieldSindico.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Nome ou Síndico estão vazios, favor preencher!");
        } else {
            CondominioDAO j = DAOFactory.getDAOFactory().getCondominioDAO();
            j.atualizar(c);
            JOptionPane.showMessageDialog(null, "Condomínio Editado com Sucesso!");
            limparCampos();
            bloquearCampos();
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        Condominio condominio = new Condominio();
        condominio.setCodCondominio(Integer.parseInt(jTextFieldCodigo.getText()));
        CondominioDAO j = DAOFactory.getDAOFactory().getCondominioDAO();
        j.excluir(condominio);
        JOptionPane.showMessageDialog(null, "Condomínio Excluído com Sucesso!");
        limparCampos();
        bloquearCampos();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        CondominioDAO j = DAOFactory.getDAOFactory().getCondominioDAO();
        int a = Integer.parseInt(jTextFieldCodigo.getText());

        try {
            Condominio condominio = j.anterior(a);
            jTextFieldCodigo.setText(condominio.getCodCondominio().toString());
            jTextFieldNome.setText(condominio.getNomeCondominio());
            jTextFieldEndereco.setText(condominio.getEnderecoCondominio());
            jTextFieldBairro.setText(condominio.getBairroCondominio());
            jTextFieldCidade.setText(condominio.getCidadeCondominio());
            jTextFieldUf.setText(condominio.getUfCondominio());
            jFormattedTextFieldCep.setText(condominio.getCepCondominio());
            jFormattedTextFieldFone.setText(condominio.getFoneCondominio());
            jFormattedTextFieldCnpj.setText(condominio.getCnpjCondominio());
            jTextFieldEmail.setText(condominio.getEmailCondominio());
            jTextFieldSindico.setText(condominio.getSindicoCondominio());
            jTextFieldInstrucao1.setText(condominio.getInstrucao1());
            jTextFieldInstrucao2.setText(condominio.getInstrucao2());
            jTextFieldInstrucao3.setText(condominio.getInstrucao3());
            jTextFieldInstrucao4.setText(condominio.getInstrucao4());
            jFormattedTextFieldMora.setText(condominio.getMoraCondominio().toString());
            jFormattedTextFieldMulta.setText(condominio.getMultaCondominio().toString());
            jFormattedTextFieldRateio.setText(condominio.getRateioCondominio().toString());
            jTextFieldDiaVencto.setText(condominio.getDiaVencimento());
            jButtonNovo.setEnabled(false);
            desbloquearCampos();
            jButtonSalvar.setEnabled(false);
            //JOptionPane.showMessageDialog(null, "Registro Encontrado!");
        } catch (NullPointerException e) {
            limparCampos();
            JOptionPane.showMessageDialog(null, "Registro não existe!");
        }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void msg(JTextField jt, String m) {
        if (jt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, m);
            jt.requestFocus();
        }
    }

    private String validarDoubleValor(JFormattedTextField j) {
        if (new Formatados().verificarSeEntradaENumeroDouble(new Formatados().tirarAVirgulaDoValor(j.getText()))) {
            Double numero = new Formatados().formatarValorStringParaDouble(j.getText());
            return String.valueOf(numero);
        }
        return null;
    }

    private void limparCampos() {
        jTextFieldCodigo.setText("");
        jTextFieldNome.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jFormattedTextFieldCep.setText("");
        jTextFieldUf.setText("");
        jFormattedTextFieldFone.setText("");
        jFormattedTextFieldMora.setText("");
        jFormattedTextFieldMulta.setText("");
        jFormattedTextFieldRateio.setText("");
        jTextFieldSindico.setText("");
        jFormattedTextFieldCnpj.setText("");
        jTextFieldEmail.setText("");
        jTextFieldDiaVencto.setText("");
        jTextFieldInstrucao1.setText("");
        jTextFieldInstrucao2.setText("");
        jTextFieldInstrucao3.setText("");
        jTextFieldInstrucao4.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldCnpj;
    private javax.swing.JFormattedTextField jFormattedTextFieldFone;
    private javax.swing.JFormattedTextField jFormattedTextFieldMora;
    private javax.swing.JFormattedTextField jFormattedTextFieldMulta;
    private javax.swing.JFormattedTextField jFormattedTextFieldRateio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDiaVencto;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldInstrucao1;
    private javax.swing.JTextField jTextFieldInstrucao2;
    private javax.swing.JTextField jTextFieldInstrucao3;
    private javax.swing.JTextField jTextFieldInstrucao4;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldSindico;
    private javax.swing.JTextField jTextFieldUf;
    // End of variables declaration//GEN-END:variables
}